# Generated by Django 5.0.4 on 2024-04-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20240414_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='nickname',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='닉네임'),
        ),
    ]
