# Generated by Django 5.0.4 on 2024-04-16 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_comment_writer'),
        ('board', '0003_noticeboardpost_imgfile'),
    ]

    operations = [
    ]
